//ACTION REDUCER
export const GET_DATA_BY_PAGE = "GET_DATA_BY_PAGE"
export const SHOW_TAG = 'SHOW_TAG'
export const COME_DEFAULT = "COME_DEFAULT"
export const GET_TAGLIST = "GET_TAGLIST"
export const SET_DEFAULT = "SET_DEFAULT"
export const CHANGE_STATUS_LOADING = "CHANGE_STATUS_LOADING"
//ACTION SAGA
export const GET_SUCCESS = "GET_SUCCESS"
export const GET_FAIL = "GET_FAIL"
//saga by tag
export const GET_SUCCESS_BY_TAG = "GET_SUCCESS_BY_TAG"
export const GET_FAIL_BY_TAG = "GET_FAIL_BY_TAG"
//saga default
export const GET_SUCCESS_DEFAULT = "GET_SUCCESS_DEFAULT"
export const GET_FAIL_DEFAULT = "GET_FAIL_DEFAULT"
//saga by page
export const GET_DATA_PAGE_SUCCESS = "GET_DATA_PAGE_SUCCESS"
export const GET_DATA_PAGE_FAIL = "GET_DATA_PAGE_FAIL"
//
export const TO_COMMENT_PAGE = "TO_COMMENT_PAGE"
export const GET_DATA_COMMENT_SUCCESS = "GET_DATA_COMMENT_SUCCESS"
export const GET_DATA_COMMENT_FAIL = "GET_DATA_COMMENT_FAIL"
//
export const SET_TOKEN = "SET_TOKEN"
export const SET_TOKEN_SUCCESS = "SET_TOKEN_SUCCESS"
export const SET_TOKEN_FAIL = "SET_TOKEN_FAIL"
//
export const GET_DATA_BY_SLUG = "GET_DATA_BY_SLUG"
export const POST_SUCCESS = "POST_SUCCESS"
export const POST = "POST"
export const POST_FAIL = "POST_FAIL"